name: Flutter Test & Codecov Coverage

on:
  push:
    branches: [ main, master, dev-daniel ]
  pull_request:
    branches: [ main, master ]

jobs:
  coverage:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio (v4.2.2)
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      # 2. Configurar el entorno de Flutter (v2.12.0)
      - name: Set up Flutter
        uses: subosito/flutter-action@f2c4840821038e23193e62030d9224f8d68d184d
        with:
          flutter-version: '3.x'
          channel: 'stable'
          cache: true

      # 3. Obtener dependencias de Flutter
      - name: Install dependencies
        run: flutter pub get

      # 4. Ejecutar pruebas unitarias y generar el archivo coverage/lcov.info
      - name: Run Flutter tests with coverage
        run: flutter test --coverage

      # 5. Subir el reporte lcov.info a Codecov (v5.5.1)
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@b9b00868f037dd71df9f08f81014a0f443586c71
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage/lcov.info
          fail_ci_if_error: true